export class ItemCardView {
        item_id:string
        name:string
        type:string
        description:string
        price:string
        longitude:string
        latitude:string
        image_1:string
        image_2:string
        image_3:string
        image_4:string
        image_5:string
        image_6:string
        image_7:string
        image_8:string
        is_special_discount:string
        discount_price:string
        is_active:string
        expire_date:string
        showroom_id:string
        city_id:string
        user_id:string
        mobile_1:string
        mobile_2:string
        district_id:string
        showroom_name:string
        email:string
        address:string
        city_name:string
        banner_image:string
        whatsapp:string
        facebook:string
        comment:string
        rate:string
        }